
#ifndef DECLARATION_H
#define DECLARATION_H

extern const int INITIALIZE_TOKEN_COUNT_MINIMUM;

extern const int CHECK_VARIABLE_INITIALIZATION_INDEX;
extern const int CHECK_ARRAY_INITIALIZATION_INDEX;

extern const int INITIALIZE_VARIABLE_START_INDEX;
extern const int INITIALIZE_ARRAY_START_INDEX;

#endif